### ISSUE TITLE
Add link to GitHub on http://compprag.christopherpotts.net/swda.html

### ISSUE THREAD

**Issue by brandonmburroughs** [cgpotts/swda#4]
Hey @cgpotts.  Thanks so much for making this data easily available and creating a nice interface to load/work with it!  It's made my life much easier.

I was wondering if you wouldn't mind adding a link to your GitHub on http://compprag.christopherpotts.net/swda.html.  When I was originally working with this dataset, I came across your webpage but was unaware of the GitHub.  The code references on your website is a bit old (e.g. Python2 and uses an older version of `nltk` with a different `Tree` API), so I spent some time making the necessary changes.  A simple mention of the updated code on GitHub would be good.  That would save everyone the trouble of tracking down the necessary changes and allow them to continue leveraging your work.

Thanks again for providing this data and code!

**Comment by cgpotts** [comment]
@brandonmburroughs Good thought! I've now added such a link.

**Comment by brandonmburroughs** [comment]
Awesome! Thanks :+1:!
